services:
  - type: web
    name: tiktok-research-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: CLIENT_KEY
        sync: false
      - key: CLIENT_SECRET
        sync: false
